let me=null,current={type:null,id:null,name:null};
let socket = null;

try {
  if (typeof io === "function") {
    socket = io();
  }
} catch (e) {
  console.error("Socket.IO:", e);
}
const $=x=>document.querySelector(x), content=$("#content");
async function api(url,opt={}){let r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt});let d=await r.json();if(!r.ok)throw new Error(d.error||"Error");return d}
async function init(){let d=await api("/api/me");if(!d.user)return;me=d.user;$("#login").classList.add("hidden");$("#app").classList.remove("hidden");$("#me").innerHTML=`<div class="avatar">${me.avatar||me.display_name[0]}</div><b>${escapeHTML(me.display_name)}</b><small>${me.is_admin?'♛ admin':'● private account'}</small>`;if(me.is_admin)$("#adminNav").classList.remove("hidden");socket.emit("join",me.id);loadHome();loadOnline()}
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/login",{method:"POST",body:JSON.stringify({username:$("#username").value,password:$("#password").value})});location.reload()}catch(x){alert(x.message)}};
$("#logout").onclick=async()=>{await api("/api/logout",{method:"POST"});location.reload()};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");({home:loadHome,friends:loadFriends,groups:loadGroups,memories:loadMemories,admin:loadAdmin}[b.dataset.view])()});
async function loadHome(){current={};$("#title").textContent="Home";content.innerHTML=`<div class="home"><div class="welcome glass"><div><span class="eyebrow">WELCOME BACK, ${escapeHTML(me.display_name).toUpperCase()}</span><h2>Faqat bizning<br><span style="color:#8d7bff">kichik olamimiz.</span></h2><p>Bu yopiq ijtimoiy makon — begonalarsiz. Do‘stlaring bilan yozish, guruhlar yaratish, xotiralarni saqlash va birga vaqt o‘tkazish uchun.</p></div></div><div class="cards"><div class="card glass"><span class="eyebrow">PRIVATE</span><h3>🔒 Yopiq makon</h3><p>Faqat admin yaratgan accountlar tizimga kira oladi.</p></div><div class="card glass"><span class="eyebrow">CHAT</span><h3>💬 Real-time</h3><p>Do‘stlar bilan jonli suhbatlar va guruh chatlari.</p></div><div class="card glass"><span class="eyebrow">ADMIN</span><h3>♛ Boshqaruv</h3><p>Admin panel orqali do‘stlar accountlari va guruhlarni boshqarish.</p></div></div><div class="section"><div class="section-head"><h2>Tezkor kirish</h2></div><div id="homeFriends" class="user-list"></div></div></div>`;let fs=await api("/api/friends");$("#homeFriends").innerHTML=fs.slice(0,4).map(userHTML).join("")}
function userHTML(u){return `<div class="user glass" onclick="openChat(${u.id},'${escapeJS(u.display_name)}')"><div class="avatar">${escapeHTML(u.avatar||u.display_name[0])}</div><div><b>${escapeHTML(u.display_name)}</b><small>@${escapeHTML(u.username)}</small></div><span style="margin-left:auto;color:#6fe5a0">●</span></div>`}
async function loadFriends(){current={};$("#title").textContent="Friends";let fs=await api("/api/friends");content.innerHTML=`<div class="section"><div class="section-head"><h2>Do‘stlar</h2></div><div class="user-list">${fs.map(userHTML).join("")}</div></div>`}
async function loadOnline(){let fs=await api("/api/friends");$("#online").innerHTML=fs.map(u=>`<div class="user" onclick="openChat(${u.id},'${escapeJS(u.display_name)}')"><div class="avatar">${escapeHTML(u.avatar||u.display_name[0])}</div><div><b>${escapeHTML(u.display_name)}</b><small>online</small></div></div>`).join("")}
async function openChat(id,name){current={type:"dm",id,name};$("#title").textContent=name;let msgs=await api("/api/messages/"+id);renderChat(msgs,name,false);socket.emit("join",""+me.id)}
function renderChat(msgs,name,group){content.innerHTML=`<div class="chat glass"><div class="chat-head"><div class="avatar">${escapeHTML(name[0]||'G')}</div><div><h2>${escapeHTML(name)}</h2><small>${group?"group":"● private chat"}</small></div></div><div class="messages" id="messages">${msgs.map(messageHTML).join("")}</div><form class="composer" id="composer"><input id="msg" placeholder="Xabar yozing..." autocomplete="off"><button>Yuborish ↑</button></form></div>`;$("#composer").onsubmit=async e=>{e.preventDefault();let text=$("#msg").value.trim();if(!text)return;$("#msg").value="";let url=group?`/api/groups/${current.id}/messages`:"/api/messages";let body=group?{text}:{receiver_id:current.id,text};let m=await api(url,{method:"POST",body:JSON.stringify(body)});appendMessage(m)};$("#messages").scrollTop=999999}
function messageHTML(m){return `<div class="bubble ${m.sender_id===me.id?"mine":""}"><b>${m.sender_id===me.id?"Siz":escapeHTML(m.display_name)}</b><div>${escapeHTML(m.text)}</div><small>${new Date(m.created_at).toLocaleString()}</small></div>`}
function appendMessage(m){let box=$("#messages");if(box){box.insertAdjacentHTML("beforeend",messageHTML(m));box.scrollTop=999999}}
socket.on("message",m=>{if(current.type==="dm" && (m.sender_id===current.id || m.receiver_id===current.id))appendMessage(m)});
socket.on("group_message",m=>{if(current.type==="group"&&m.group_id===current.id)appendMessage(m)});
socket.on("group_deleted",id=>{if(current.type==="group"&&current.id===Number(id)){current={};loadGroups();alert('Bu guruh admin tomonidan o‘chirildi.')}});
async function loadGroups(){current={};$("#title").textContent="Groups";let gs=await api("/api/groups");content.innerHTML=`<div class="section"><div class="section-head"><h2>Guruhlar</h2><button class="create" onclick="newGroup()">+ Yangi guruh</button></div><div class="user-list">${gs.map(g=>`<div class="user glass" onclick="openGroup(${g.id},'${escapeJS(g.name)}')"><div class="avatar">◈</div><div><b>${escapeHTML(g.name)}</b><small>${g.members} member${g.members>1?"s":""}</small></div></div>`).join("")||'<p style="color:#777">Hali guruh yo‘q.</p>'}</div></div>`}
async function newGroup(){showModal("Yangi guruh",`<input id="gname" placeholder="Guruh nomi"><div class="actions"><button class="create" onclick="closeModal()">Bekor</button><button class="create" onclick="createGroup()">Yaratish</button></div>`)}
async function createGroup(){let n=$("#gname").value.trim();if(!n)return;try{await api("/api/groups",{method:"POST",body:JSON.stringify({name:n})});closeModal();loadGroups()}catch(e){alert(e.message)}}
async function openGroup(id,name){current={type:"group",id,name};let msgs=await api("/api/groups/"+id+"/messages");renderChat(msgs,name,true);socket.emit("join_group",id,me.id)}
async function loadMemories(){current={};$("#title").textContent="Memories";content.innerHTML=`<div class="section"><div class="section-head"><h2>Memory Wall</h2></div><div class="cards"><div class="card glass"><h3>☀️ Summer 2026</h3><p>Eng yaxshi kunlar rejalashtirilmaydi.</p></div><div class="card glass"><h3>🌙 Night Walk</h3><p>02:47 — hali ham uyga ketmadik.</p></div><div class="card glass"><h3>🎮 Game Night</h3><p>Rematch hali ham ochiq.</p></div></div></div>`}

async function loadAdmin(){
  if(!me?.is_admin){return loadHome()}
  current={};$("#title").textContent="Admin Panel";
  content.innerHTML=`<div class="section"><div class="section-head"><div><span class="eyebrow">OWNER CONTROL</span><h2>Admin Panel</h2></div><div class="row-actions"><button class="small-btn" onclick="changeAdminPassword()">🔑 Admin paroli</button><button class="create" onclick="newUser()">+ Do‘st accounti</button></div></div><p class="admin-note">Bu yerda do‘stlaringiz uchun login/parol yaratishingiz, parollarni yangilashingiz, accountlarni o‘chirishingiz, guruhlarni o‘chirishingiz va admin parolini almashtirishingiz mumkin.</p><div class="admin-grid"><div class="admin-card glass"><div class="section-head"><h3>👥 Do‘stlar accountlari</h3><button class="small-btn" onclick="loadAdmin()">↻</button></div><div id="adminUsers">Yuklanmoqda...</div></div><div class="admin-card glass"><div class="section-head"><h3>◈ Guruhlar</h3><button class="small-btn" onclick="loadAdmin()">↻</button></div><div id="adminGroups">Yuklanmoqda...</div></div></div></div>`;
  try{
    const [users,groups]=await Promise.all([api('/api/admin/users'),api('/api/admin/groups')]);
    $("#adminUsers").innerHTML=users.map(u=>`<div class="admin-row"><div class="avatar">${escapeHTML(u.avatar||u.display_name[0])}</div><div class="admin-info"><b>${escapeHTML(u.display_name)} ${u.is_admin?'<span class="badge">ADMIN</span>':''}</b><small>@${escapeHTML(u.username)}</small></div>${u.is_admin?'<span class="muted">Himoyalangan</span>':`<div class="row-actions"><button class="small-btn" onclick="resetPassword(${u.id},'${escapeJS(u.display_name)}')">Parol</button><button class="danger" onclick="deleteUser(${u.id},'${escapeJS(u.display_name)}')">O‘chirish</button></div>`}</div>`).join('')||'<p class="muted">Accountlar yo‘q.</p>';
    $("#adminGroups").innerHTML=groups.map(g=>`<div class="admin-row"><div class="avatar">◈</div><div class="admin-info"><b>${escapeHTML(g.name)}</b><small>${g.members} a’zo · yaratuvchi: ${escapeHTML(g.creator)}</small></div><button class="danger" onclick="deleteGroup(${g.id},'${escapeJS(g.name)}')">O‘chirish</button></div>`).join('')||'<p class="muted">Guruhlar yo‘q.</p>';
  }catch(e){content.innerHTML+=`<p class="error">${escapeHTML(e.message)}</p>`}
}
async function newUser(){showModal('Yangi do‘st accounti',`<p class="muted">Do‘stingizga berish uchun login va parol yarating.</p><input id="newName" placeholder="Ism, masalan: Ali"><input id="newUsername" placeholder="Username, masalan: ali"><input id="newPassword" type="password" placeholder="Parol (kamida 6 belgi)"><div class="actions"><button class="create" onclick="closeModal()">Bekor</button><button class="create" onclick="createUser()">Account yaratish</button></div>`)}
async function createUser(){try{const name=$("#newName").value.trim(),username=$("#newUsername").value.trim(),password=$("#newPassword").value;const d=await api('/api/admin/users',{method:'POST',body:JSON.stringify({display_name:name,username,password})});closeModal();alert(`Account yaratildi!\nLogin: ${d.user.username}\nParol: ${password}`);loadAdmin()}catch(e){alert(e.message)}}
async function resetPassword(id,name){showModal(`${escapeHTML(name)} — yangi parol`,`<input id="resetPass" type="password" placeholder="Yangi parol (kamida 6 belgi)"><div class="actions"><button class="create" onclick="closeModal()">Bekor</button><button class="create" onclick="savePassword(${id})">Saqlash</button></div>`)}
async function savePassword(id){try{const password=$("#resetPass").value;await api('/api/admin/users/'+id+'/password',{method:'POST',body:JSON.stringify({password})});closeModal();alert('Parol yangilandi.');loadAdmin()}catch(e){alert(e.message)}}
async function changeAdminPassword(){showModal('Admin parolini almashtirish',`<p class="muted">Admin login: <b>badbro</b></p><input id="currentAdminPass" type="password" placeholder="Joriy parol"><input id="newAdminPass" type="password" placeholder="Yangi parol (kamida 6 belgi)"><input id="newAdminPass2" type="password" placeholder="Yangi parolni takrorlang"><div class="actions"><button class="create" onclick="closeModal()">Bekor</button><button class="create" onclick="saveAdminPassword()">Saqlash</button></div>`)}
async function saveAdminPassword(){try{const currentPassword=$("#currentAdminPass").value,newPassword=$("#newAdminPass").value,again=$("#newAdminPass2").value;if(newPassword!==again)return alert('Yangi parollar bir xil emas.');await api('/api/admin/password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});closeModal();alert('Admin paroli yangilandi. Keyingi kirishda yangi paroldan foydalaning.')}catch(e){alert(e.message)}}
async function deleteUser(id,name){if(!confirm(`${name} accountini o‘chirmoqchimisiz?\nUning xabarlari va guruh a’zoligi ham o‘chiriladi.`))return;try{await api('/api/admin/users/'+id,{method:'DELETE'});loadAdmin();loadOnline()}catch(e){alert(e.message)}}
async function deleteGroup(id,name){if(!confirm(`${name} guruhini butunlay o‘chirmoqchimisiz?\nGuruh xabarlari ham o‘chiriladi.`))return;try{await api('/api/admin/groups/'+id,{method:'DELETE'});loadAdmin()}catch(e){alert(e.message)}}
function showModal(title,html){$("#modal").classList.remove("hidden");$("#modal").innerHTML=`<div class="modalbox glass"><h2 style="font-family:Space Grotesk">${title}</h2>${html}</div>`}function closeModal(){$("#modal").classList.add("hidden")}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function escapeJS(s){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\n/g,' ')}
$("#theme").onclick=()=>document.body.classList.toggle("light");init();
